import type { AgentProfile, AIAnalysis, ClientRow, ListingItem, ListingRequest, TenantProfile } from "./types";

export const mockAgent: AgentProfile = {
  id: "agent_1",
  fullName: "Azeem Mustafa",
  firstName: "Azeem",
  email: "azeem@example.com",
  phone: "416-555-0123",
  recoLicense: "RECO-123456",
  verified: true,
  referralUrl: "https://yourapp.com/signup?ref=agent_1",
};

export const mockTenant: TenantProfile = {
  id: "tenant_1",
  fullName: "Zain Tariq",
  email: "zain@example.com",
  phone: "647-555-0199",
  dob: "2004-06-10",
  occupation: "Program Coordinator",
  employer: "Healthcare Nonprofit",
  creditScore: 712,
  annualIncome: 78000,
  requestedMoveIn: "2026-02-15",
  immigrationStatus: "Canadian Citizen",
  tenantStatus: "Active",
  coApplicantOrGuarantor: false,
  bio: "Quiet, clean, and respectful tenant. Looking for a long-term lease.",
  docs: [
    { type: "Driver's License", required: true, uploaded: true, note: "Auto-extracted name/DOB/address" },
    { type: "Equifax Credit Report", required: true, uploaded: true },
    { type: "Pay Stub #1", required: true, uploaded: true },
    { type: "Pay Stub #2", required: true, uploaded: false, note: "Missing one recent pay stub" },
    { type: "Letter of Employment", required: true, uploaded: true },
    { type: "Rental Application (PDF)", required: true, uploaded: false, note: "Fillable PDF not uploaded yet" },
    { type: "Notice of Assessment (Optional)", required: false, uploaded: false },
  ],
  properties: [
    {
      id: "p1",
      address: "12 King St W, Toronto, ON",
      rent: 2800,
      status: "Viewing Requested",
      dateRequested: "2026-01-18",
      lastUpdate: "2026-01-18",
    },
    {
      id: "p2",
      address: "88 Lakeshore Blvd, Toronto, ON",
      rent: 3100,
      status: "Applied",
      dateRequested: "2026-01-10",
      dateViewed: "2026-01-12",
      dateApplied: "2026-01-14",
      lastUpdate: "2026-01-14",
    },
  ],
};

export const mockListings: ListingItem[] = [
  {
    id: "l1",
    mlsNumber: "C8421134",
    address: "12 King St W",
    city: "Toronto",
    province: "ON",
    rent: 2950,
    beds: 2,
    baths: 2,
    sqft: 890,
    homeType: "Condo",
    yearBuilt: 2016,
    parking: "1 underground",
    daysOnMarket: 9,
    description:
      "Bright corner suite with floor-to-ceiling windows, open-concept kitchen, and a wraparound balcony. Walk to PATH, TTC, and the waterfront.",
    features: ["Balcony", "Ensuite laundry", "Concierge", "Gym", "Rooftop deck"],
    images: [
      "https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80",
    ],
  },
  {
    id: "l2",
    mlsNumber: "W8429011",
    address: "88 Lakeshore Blvd",
    city: "Toronto",
    province: "ON",
    rent: 3200,
    beds: 1,
    baths: 1,
    sqft: 675,
    homeType: "Condo",
    yearBuilt: 2019,
    parking: "None",
    daysOnMarket: 3,
    description:
      "Modern lakeview suite with sleek finishes and built-in appliances. Steps to the boardwalk, cafes, and transit.",
    features: ["Lake view", "Smart lock", "Bike storage", "Party room", "Pet friendly"],
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1481277542470-605612bd2d61?auto=format&fit=crop&w=1400&q=80",
    ],
  },
  {
    id: "l3",
    mlsNumber: "E8435120",
    address: "452 Gerrard St E",
    city: "Toronto",
    province: "ON",
    rent: 3450,
    beds: 3,
    baths: 2,
    sqft: 1180,
    homeType: "Townhome",
    yearBuilt: 2008,
    parking: "1 garage",
    daysOnMarket: 14,
    description:
      "Renovated townhome with a private patio, chef's kitchen, and finished basement flex space. Ideal for roommates or small families.",
    features: ["Private patio", "Finished basement", "Gas range", "Storage locker", "Transit nearby"],
    images: [
      "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=80",
    ],
  },
];

export const mockListingRequests: ListingRequest[] = [
  {
    id: "r1",
    listingId: "l1",
    listingAddress: "12 King St W, Toronto, ON",
    tenantName: "Zain Tariq",
    type: "Viewing",
    createdAt: "2026-01-27",
    status: "Pending",
    preferredViewingDate: "2026-02-03",
  },
  {
    id: "r2",
    listingId: "l2",
    listingAddress: "88 Lakeshore Blvd, Toronto, ON",
    tenantName: "Zain Tariq",
    type: "Offer",
    createdAt: "2026-01-26",
    status: "Submitted",
    offerPrice: 3100,
    moveInDate: "2026-03-01",
    stage: "In Review",
  },
  {
    id: "r3",
    listingId: "l3",
    listingAddress: "452 Gerrard St E, Toronto, ON",
    tenantName: "Sarah Chen",
    type: "Offer",
    createdAt: "2026-01-25",
    status: "Submitted",
    offerPrice: 3350,
    moveInDate: "2026-02-15",
    stage: "Submitted to Landlord",
  },
];

export const mockAI: AIAnalysis = {
  risk: "Yellow",
  summary: [
    "Credit score meets threshold (>= 700).",
    "Income appears sufficient (>= 2x rent) for most listings.",
    "One required document missing (Pay Stub #2).",
    "No collections detected in provided report (mock).",
  ],
  overridesAllowed: true,
};

export const mockClients: ClientRow[] = [
  {
    clientId: "tenant_1",
    fullName: "Zain Tariq",
    status: "Active",
    phone: "647-555-0199",
    creditScore: 712,
    combinedAnnualIncome: 78000,
    notesPreview: "Strong profile. Missing one pay stub.",
    propertiesSummary: "Requested: 1 | Viewed: 1 | Applied: 1",
    unlocked: true,
  },
  {
    clientId: "tenant_2",
    fullName: "Sarah Chen",
    status: "Viewing",
    phone: "416-555-0440",
    creditScore: 690,
    combinedAnnualIncome: 92000,
    notesPreview: "Borderline credit, good income.",
    propertiesSummary: "Requested: 2 | Viewed: 0 | Applied: 0",
    unlocked: false,
  },
];
